// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"github.com/gin-gonic/gin"
)

// PostAddJSONBody defines parameters for PostAdd.
type PostAddJSONBody struct {
	Number1 *int `json:"number1,omitempty"`
	Number2 *int `json:"number2,omitempty"`
}

// PostDivideJSONBody defines parameters for PostDivide.
type PostDivideJSONBody struct {
	Dividend *int `json:"dividend,omitempty"`
	Divisor  *int `json:"divisor,omitempty"`
}

// PostMultiplyJSONBody defines parameters for PostMultiply.
type PostMultiplyJSONBody struct {
	Number1 *int `json:"number1,omitempty"`
	Number2 *int `json:"number2,omitempty"`
}

// PostSubtractJSONBody defines parameters for PostSubtract.
type PostSubtractJSONBody struct {
	Number1 *int `json:"number1,omitempty"`
	Number2 *int `json:"number2,omitempty"`
}

// PostSumJSONBody defines parameters for PostSum.
type PostSumJSONBody = []int

// PostAddJSONRequestBody defines body for PostAdd for application/json ContentType.
type PostAddJSONRequestBody PostAddJSONBody

// PostDivideJSONRequestBody defines body for PostDivide for application/json ContentType.
type PostDivideJSONRequestBody PostDivideJSONBody

// PostMultiplyJSONRequestBody defines body for PostMultiply for application/json ContentType.
type PostMultiplyJSONRequestBody PostMultiplyJSONBody

// PostSubtractJSONRequestBody defines body for PostSubtract for application/json ContentType.
type PostSubtractJSONRequestBody PostSubtractJSONBody

// PostSumJSONRequestBody defines body for PostSum for application/json ContentType.
type PostSumJSONRequestBody = PostSumJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Add two numbers
	// (POST /add)
	PostAdd(c *gin.Context)
	// Divide two numbers
	// (POST /divide)
	PostDivide(c *gin.Context)
	// Multiply two numbers
	// (POST /multiply)
	PostMultiply(c *gin.Context)
	// Subtract two numbers
	// (POST /subtract)
	PostSubtract(c *gin.Context)
	// Add all numbers in an array
	// (POST /sum)
	PostSum(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostAdd operation middleware
func (siw *ServerInterfaceWrapper) PostAdd(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAdd(c)
}

// PostDivide operation middleware
func (siw *ServerInterfaceWrapper) PostDivide(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostDivide(c)
}

// PostMultiply operation middleware
func (siw *ServerInterfaceWrapper) PostMultiply(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostMultiply(c)
}

// PostSubtract operation middleware
func (siw *ServerInterfaceWrapper) PostSubtract(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSubtract(c)
}

// PostSum operation middleware
func (siw *ServerInterfaceWrapper) PostSum(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSum(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/add", wrapper.PostAdd)
	router.POST(options.BaseURL+"/divide", wrapper.PostDivide)
	router.POST(options.BaseURL+"/multiply", wrapper.PostMultiply)
	router.POST(options.BaseURL+"/subtract", wrapper.PostSubtract)
	router.POST(options.BaseURL+"/sum", wrapper.PostSum)
}
